---
- name: Create Consul service definition
  include_role: name=consul-service
  vars:
    consul_config_name: '{{ es_service_name }}'
    consul_services:
      - name: '{{ es_service_name }}'
        tags: ['{{ env }}.{{ stage }}', '{{ es_cluster_name }}']
        # we advertise the port with basic auth
        port: '{{ es_api_port }}'
        address: '{{ ansible_local.wireguard.vpn_ip }}'
        meta:
            fleet: '{{ env }}.{{ stage }}'
            cluster_port: '{{ es_node_port | string }}'
            cluster_name: '{{ es_cluster_name }}'
        checks:
          - id: '{{ es_service_name }}-health'
            name: ElasticSearch Healthcheck
            type: http
            http: 'http://localhost:{{ es_api_port }}/_cluster/health?pretty'
            interval: '60s'
            timeout: '5s'

- name: Create Consul service definition
  include_role: name=consul-service
  vars:
    consul_config_name: '{{ es_exp_cont_name }}'
    consul_services:
      - name: '{{ es_exp_cont_name }}'
        tags: ['{{ env }}.{{ stage }}', '{{ es_cluster_name }}', 'metrics']
        # we advertise the port with basic auth
        port: '{{ es_exp_cont_port }}'
        address: '{{ ansible_local.wireguard.vpn_ip }}'
        meta:
            fleet: '{{ env }}.{{ stage }}'
            cluster_name: '{{ es_cluster_name }}'
        checks:
          - id: '{{ es_exp_cont_name }}-health'
            name: ES metrics exporter healthcheck
            type: http
            http: 'http://localhost:{{ es_exp_cont_port }}/healthz'
            interval: '60s'
            timeout: '5s'
