---
- name: 'Create data folder for container: {{ es_cont_name }}'
  file:
    path: '{{ es_docker_dir }}/data'
    state: directory
    owner: '{{ es_host_uid }}'
    group: docker
    mode: 0775
    recurse: true

- name: 'Start container: {{ es_cont_name }}'
  docker_container:
    name: '{{ es_cont_name }}'
    image: '{{ es_image }}'
    pull: true
    restart_policy: always
    state: '{{ cont_state }}'
    recreate: '{{ cont_recreate }}'
    restart: '{{ es_config.changed | default(cont_restart) }}'
    ports:
      - '0.0.0.0:{{ es_api_port }}:{{ es_api_port }}'
      - '0.0.0.0:{{ es_node_port }}:{{ es_node_port }}'
    volumes:
      - '{{ es_docker_dir }}/conf/:/usr/share/elasticsearch/config'
      - '{{ es_docker_dir }}/data/:/usr/share/elasticsearch/data'
