---
- name: 'Create container folders'
  file:
    path:  '{{ item.path }}'
    owner: '{{ item.owner | default(es_node_host_uid) }}'
    group: 'docker'
    mode:  '0o750'
    state: 'directory'
  with_items:
    - { path: '{{ es_node_host_backup_path }}' }
    - { path: '{{ es_node_host_data_path }}' }
    - { path: '{{ es_transport_certs_path }}' }

- name: 'Create compose file'
  template:
    src:   'docker-compose.yml.j2'
    dest:  '{{ es_compose_path }}'
    owner: 'dockremap'
    group: 'docker'
    mode:  '0o644'

- name: 'Create containers'
  community.docker.docker_compose_v2:
    project_src: '{{ es_service_path }}'
    recreate:    '{{ compose_recreate }}'
    pull:        '{{ compose_pull }}'
    state:       '{{ es_config.changed | ternary("restarted", compose_state) }}'
