---
- name: 'Create container folders'
  file:
    path: '{{ item.path }}'
    owner: '{{ item.owner }}'
    group: docker
    mode: 0750
    state: directory
    recurse: true
  with_items:
    - { path: '{{ es_node_cont_vol }}/backup', owner: '{{ es_node_host_uid }}' }
    - { path: '{{ es_node_cont_vol }}/data',   owner: '{{ es_node_host_uid }}' }
    - { path: '{{ es_hq_cont_vol }}/conf',     owner: 'dockremap' }

- name: Copy over logging config
  copy:
    src: 'hq/logger.json'
    dest: '{{ es_hq_cont_vol }}/conf/logger.json'
    owner: dockremap
    group: docker
    mode: 0644


- name: 'Create compose file'
  template:
    src: 'docker-compose.yml.j2'
    dest: '{{ es_compose_path }}'
    owner: dockremap
    group: docker
    mode: 0644

- name: 'Create containers'
  docker_compose:
    project_src: '{{ es_service_path }}'
    state: '{{ compose_state }}'
    restarted: '{{ compose_restart }}'
    recreate: '{{ es_config.changed | ternary("always", compose_recreate) }}'
    pull: true
    build: false
