---
- name: 'Create container folders'
  file:
    path: '{{ item.path }}'
    owner: '{{ item.owner }}'
    group: docker
    mode: 0750
    state: directory
    recurse: true
  with_items:
    - { path: '{{ es_node_cont_vol }}/backup', owner: '{{ es_node_host_uid }}' }
    - { path: '{{ es_node_cont_vol }}/data',   owner: '{{ es_node_host_uid }}' }

- name: 'Create compose file'
  template:
    src: 'docker-compose.yml.j2'
    dest: '{{ es_compose_path }}'
    owner: dockremap
    group: docker
    mode: 0644

- name: 'Create containers'
  community.docker.docker_compose_v2:
    project_src: '{{ es_service_path }}'
    recreate:    '{{ compose_recreate }}'
    pull:        '{{ compose_pull }}'
    state:       '{{ es_config.changed | ternary("restarted", compose_state) }}'
