---
- name: Wait for ElasticSearch HTTP port to go up
  wait_for:
    port: '{{ es_api_port }}'
    delay: 5
    timeout: 10

- name: 'Set number of replicas to {{ es_number_of_replicas }} for all new indices'
  uri:
    url: 'http://localhost:{{ es_api_port }}/_template/default_template'
    method: PUT
    status_code: 200
    body_format: json
    body: |
      {
        "index_patterns": ["*"],
        "mappings": {{ es_default_template_mappings | to_json }},
        "settings": {
          "number_of_replicas": {{ es_number_of_replicas | to_json }},
          "number_of_shards": {{ es_number_of_shards | to_json }}
        }
      }
